version: 2

before:
  hooks:
    - go mod tidy
    - mkdir -p man

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/Erl-koenig/switchdl/cmd.version={{.Version}}
    hooks:
      post:
        - |
          if [ "{{ .Os }}" = "linux" ] && [ "{{ .Arch }}" = "amd64" ]; then
            "{{ .Path }}" man
            test -f man/switchdl.1 || (echo "manpage not generated!" && exit 1)
          fi

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - man/*
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

homebrew_casks:
  - name: switchdl
    homepage: https://github.com/Erl-koenig/switchdl
    description: "A CLI tool for downloading videos from SwitchTube"
    license: MIT
    directory: Casks
    repository:
      owner: Erl-koenig
      branch: main
      name: homebrew-switchdl
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    custom_block: |
      manpages = Dir["#{prefix}/man/*"]
      man1.install manpages
