version: 2

before:
  hooks:
    - go mod tidy
    - mkdir -p man
    - go run main.go man

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/Erl-koenig/switchdl/cmd.version={{.Version}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - man/*
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

homebrew_casks:
  - name: switchdl
    homepage: https://github.com/Erl-koenig/switchdl
    description: "A CLI tool for downloading videos from SwitchTube"
    license: MIT
    directory: Casks
    repository:
      owner: Erl-koenig
      branch: main
      name: homebrew-switchdl
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    manpages:
      - man/switchdl.1
      - man/switchdl-video.1
      - man/switchdl-channel.1
      - man/switchdl-version.1
      - man/switchdl-configure.1
      - man/switchdl-configure-show.1
      - man/switchdl-configure-delete.1
      - man/switchdl-configure-validate.1
      - man/switchdl-man.1
      - man/switchdl-completion.1
      - man/switchdl-completion-bash.1
      - man/switchdl-completion-fish.1
      - man/switchdl-completion-powershell.1
      - man/switchdl-completion-zsh.1
